server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    prefix: classpath:/templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blog?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 10

  jackson:
    serialization:
      fail-on-empty-beans: false

  logging.level:
    org.hibernate.SQL : debug

  kafka:
    bootstrap-servers: localhost:9092  #kakfa 서버정보 / port 9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # producer에서 kafka로 전달할때 사용하는 key값
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # producer에서 kafka로 전달할때 사용하는 value값
      acks: 1

    template:
      default-topic: testTopic # 기본설정 topic name


